// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stockma.Infrastructure.Persistence;

#nullable disable

namespace Stockma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockmaDbContext))]
    [Migration("20260902071811_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stockma.Domain.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("current_quantity");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("LocationShelf")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_shelf");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lot_number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductId", "ExpirationDate")
                        .HasDatabaseName("ix_batches_product_expiration");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("Stockma.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveIngredient")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("active_ingredient");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Presentation")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("presentation");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("StorageConditions")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("storage_conditions");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_sku");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Stockma.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Stockma.Domain.Entities.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("MaxTrustedDevices")
                        .HasColumnType("integer")
                        .HasColumnName("max_trusted_devices");

                    b.Property<int>("NextSkuNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_sku_number");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("Stockma.Domain.Entities.Batch", b =>
                {
                    b.HasOne("Stockma.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stockma.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stockma.Domain.Entities.Product", b =>
                {
                    b.HasOne("Stockma.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stockma.Domain.Entities.TenantSettings", b =>
                {
                    b.HasOne("Stockma.Domain.Entities.Tenant", null)
                        .WithOne("Settings")
                        .HasForeignKey("Stockma.Domain.Entities.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Stockma.Domain.ValueObjects.ExpiryThresholds", "Thresholds", b1 =>
                        {
                            b1.Property<Guid>("TenantSettingsTenantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GreenMonths")
                                .HasColumnType("integer")
                                .HasColumnName("green_months");

                            b1.Property<int>("YellowMonths")
                                .HasColumnType("integer")
                                .HasColumnName("yellow_months");

                            b1.HasKey("TenantSettingsTenantId");

                            b1.ToTable("tenant_settings");

                            b1.WithOwner()
                                .HasForeignKey("TenantSettingsTenantId");
                        });

                    b.Navigation("Thresholds")
                        .IsRequired();
                });

            modelBuilder.Entity("Stockma.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
